# encoding: utf-8
puts "To create a new file using ruby you have to use the File class"
puts " like that"
puts "--------------------------------------------------------------"
puts "f = File.new 'Hello.txt' , 'w' "
puts "f.puts 'Hello this is a new file'"
puts "f.close"
puts "--------------------------------------------------------------"
puts "Whit that you create a new file named 'Hello.txt' and "
puts "write in the file the hello phrase, and then close the file"
puts "See the parameter 'w', it indicates that you are opening the file"
puts "in the writing mode"
puts "You have the following opening parameters"
puts " r -> That open in the reading mode"
puts " w -> That open in the writing mode, if the file have content it will overwrite"
puts " w+ -> That open in the writing and reading mode, if the file have "
puts "content it will overwrite if you write a content"
puts " a -> Open the file in writing mode, but it will start writing in the end of"
puts "the file"

