# encoding: utf-8
puts "You can also serialze objects in ruby , you have a library to do that"
puts "it is called YAML, you have to import the library and use it like that"
puts "----------------------------------------------------------------------"
puts "require 'yaml'"
puts "my_object = User.new name: 'Teste' , email: 'teste@teste.com'"
puts "serialized_object = YAML.dump my_object"
puts "----------------------------------------------------------------------"
puts "With that you have a object serialized, and you can save in a file"
puts "to read a serialized object is prety simple too"
puts "----------------------------------------------------------------------"
puts "my_object = YAML.load srialized_object"
puts "----------------------------------------------------------------------"
puts "And then the ruby will reconstruc your object for you"