# encoding: utf-8
puts "You can create a conditional check in ruby in the"
puts "following way"
puts "@age = 17"
puts "if @age < 18 "
puts "  puts 'You are underage'"
puts "end"
puts "-------------------------------------------------"
puts "You can also create in a single line"
puts "@age = 17"
puts "if @age < 18 then puts 'You are underage' end"
puts "-------------------------------------------------"
puts "If the test is not true you can also have a else structure"
puts "if @age < 18 "
puts "  puts 'You are underage'"
puts "else"
puts "  puts 'You are major'"
puts "end"
puts "-------------------------------------------------"
puts "You can also have a test before set a value in a variable"
puts "@age = 18"
puts "@major = true if @age > 17"
puts "-------------------------------------------------"
puts "It will set true to @major if @age is more than 17"
puts "You can check if a variable is of some type with the key "
puts "word 'kind_of?'"
puts "-------------------------------------------------"
puts "@number = 10"
puts "if @number.kind_of? Numeric"
puts "   puts 'yeah its a Numeric'"
puts "end"

