# encoding: utf-8
puts "############## LAMBDAS ###############"
puts "Lambda is a way to store a block in a variable "
puts "diferent from proc it validates the parameters before call"
puts "and a return inside a lanbda does not stop the method where"
puts "the lambda is running"
puts "you can create a lambda in the following way"
puts "#########"
puts " my_lambda = lambda do"
puts "     puts 'do somethind here'"
puts " end"
puts "#########"
puts " to execute a lambda you use call method"
puts "#########"
puts " my_lambda.call "
puts "#########"