# encoding: utf-8
puts "A Set is similar to a array it is a list of element"
puts "but a Set can't contain repeated elements in it"
puts "to create a Set you need to, import the set lib through"
puts "require 'set'"
puts "and then you instatiate a set"
puts "@my_set = Set.new"
puts "---------------------------------------------------"
puts "To add elements to the set is the same way as the array"
puts "@my_set << 1"
puts "But if you try to add the same element to the set"
puts "it will maintain only one element without repetition"
puts "---------------------------------------------------"
puts "You can also create a Set initialized with some elements"
puts "you just need to pass a array as argument"
puts "@my_set = Set.new [1,2,3,4,5]"
puts "if the array contains repeated values, the repeated values" 
puts "will be disconsidered"

